### ISSUE TITLE
Country outline on output image

### ISSUE THREAD

**Issue by jmsinusa** [Guymer/wtzscb#1]
Can you overlay the country outline on your output image? Also a leaderboard of time zone compliance would be interesting.

**Comment by Guymer** [comment]
I wrote these scripts in support of [a blog post](http://www.thomasguymer.co.uk/blog/2019/2019-07-06/) that has now been published. Perhaps the later part of that article can satisfy your interest in "time zone compliance"? Secondly, how does [step4a.png](../blob/master/step4a.png) do for your desire for country outlines? I admit that it does not have country outlines, but I personally think that the coastal outlines adds a lot. (The `step??.png` images are the figures that I used in the blog post).

**Comment by jmsinusa** [comment]
Your blog post answers my immediate questions!
